datadog:
  datadog:
    apiKey: vault:datadog-app:apiKey
    clusterName: "{{ .Requirements.cluster.clusterName }}"
    tags:
      - env: dev
      - clustername: "{{ .Requirements.cluster.clusterName }}"
    nonLocalTraffic: true
    collectEvents: true
    leaderElection: true
    logsEnabled: true
    logsConfigContainerCollectAll: true
    apmEnabled: true
    processAgentEnabled: false
    acInclude: image:gcr.io/abayer-pipeline-crd/tekton-for-jx/bash image:gcr.io/abayer-pipeline-crd/tekton-for-jx/creds-init image:gcr.io/abayer-pipeline-crd/tekton-for-jx/entrypoint image:gcr.io/abayer-pipeline-crd/tekton-for-jx/git-init image:gcr.io/jenkinsxio/builder-jx image:gcr.io/jenkinsxio/jx-tenant-service
    resources:
      requests:
        cpu: 200m
        memory: 256Mi
      limits:
        cpu: 300m
        memory: 512Mi
    confd:
      etcd.yaml: |-
        ad_identifiers:
          - etcd
        init_config:
        instances:
          - url: "http://%%host%%:2379"
  daemonset:
    useHostPort: true
