replicaCount: 2
parentDomain: {{ .Parameters.parentDomain }}
parentProject: {{ .Parameters.parentProject}}
parentDNSZone: {{ .Parameters.parentDNSZone}}
basicAuthPassword: vault:jx-tenant-service-ba:password
dbUser: jx-tenant-service
dbPassword: vault:jx-tenant-service-db:password
cloudSQLSA: vault:jx-tenant-db-client:sa
sa: vault:jx-tenant-service-sa:json
saasSA: vault:jx-tenant-service-saas-sa:json
cert: vault:lh-github-app:cert
id: vault:lh-github-app:id
dbInstance: {{ .Parameters.tenantServiceDBInstance }}
tenantFolderID: "205530701291"
service:
  serviceAnnotations:
    fabric8.io/expose: "false"
    fabric8.io/exposeUrl: https://jx-tenant-service{{ .Requirements.ingress.namespaceSubDomain }}{{ .Requirements.ingress.domain }}
segmentWriteKey: vault:segment:write-key
env:
  BOT_NAME: jenkins-x-bot[bot]
  JX_FAIL_MISSING_SIGNATURE: true

updateController:
  env:
    TRACE_KUBE_API: "true"
    JX_LOG_LEVEL: "debug"
    JX_LOG_FORMAT: "json"
