{{- if .Values.arcalos }}
apiVersion: v1
data:
  domain_issuer_password: {{ .Values.arcalos.domainIssuerPassword | b64enc | quote }} # pragma: allowlist secret
  domain_issuer_username: {{ .Values.arcalos.domainIssuerUsername | b64enc | quote }}
  pipeline_github_user: {{ .Values.arcalos.pipelineGithubUser | b64enc | quote }}
  pipeline_github_email: {{ .Values.arcalos.pipelineGithubEmail | b64enc | quote }}
  git_owner: {{ .Values.arcalos.gitOwner | b64enc | quote }}
  arcalos_prod_sa: {{ .Values.arcalos.arcalosProdSA | quote }}
  segment_write_key: {{ .Values.arcalos.segmentWriteKey | b64enc | quote }}
kind: Secret
metadata:
  name:  arcalos-alpha-prod-secret
type: Opaque
{{- end }}
