apiVersion: jenkins.io/v1
kind: Scheduler
metadata:
  creationTimestamp: null
  name: arcalos-scheduler
spec:
  approve:
    issueRequired: false
    lgtmActsAsApprove: true
    requireSelfApproval: true
  merger:
    blockerLabel: ""
    maxGoroutines: 0
    mergeMethod: merge
    policy:
      fromBranchProtection: true
      optionalContexts: {}
      requiredContexts: {}
      requiredIfPresentContexts: {}
      skipUnknownContexts: false
    prStatusBaseUrl: ""
    squashLabel: ""
    targetUrl: http://deck{{ .Values.cluster.namespaceSubDomain }}{{ .Values.cluster.domain }}
  plugins:
    entries:
    - config-updater
    - approve
    - assign
    - blunderbuss
    - help
    - hold
    - lgtm
    - lifecycle
    - size
    - trigger
    - wip
    - heart
    - cat
    - override
  policy:
    protectTested: true
  postsubmits:
    replace: true
  presubmits:
    replace: true
  schedulerAgent:
    agent: tekton
  trigger:
    ignoreOkToTest: false
    joinOrgUrl: ""
    onlyOrgMembers: false
    trustedOrg: {{ .Values.gitops.owner }}
  welcome:
  - message_template: Welcome
