apiVersion: v1
stringData:
  .dogrc: |-
    [Connection]
    apikey = {{ .Values.datadog.apiKey }}
    appkey = {{ .Values.datadog.appKey }}
kind: Secret
metadata:
  name:  datadog-dogrc-secret
type: Opaque
